export const SITE_CONFIG = {
  name: 'Ameya Sales Corporation',
  tagline: 'Premium Architectural Safety & Glass Solutions',
  shortName: 'Ameya Sales',
  description:
    'Ameya Sales Corporation — Maharashtra\'s leading manufacturer and installer of invisible grills, UPVC windows, aluminium windows, glass railings, SS railings, safety nets, bird nets, mosquito mesh, ACP cladding, pergola systems, and premium glass solutions for residential, commercial, and industrial projects.',
  url: 'https://www.ameyasalescorporation.com',
  phone: '+91 98765 43210',
  phoneDisplay: '+91 98765 43210',
  whatsapp: '919876543210',
  email: 'info@ameyasalescorporation.com',
  address: {
    street: 'Shop No. 5, Shivaji Nagar',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411005',
    country: 'India',
    full: 'Shop No. 5, Shivaji Nagar, Pune, Maharashtra 411005, India',
  },
  coordinates: {
    lat: 18.5204,
    lng: 73.8567,
  },
  gst: '27XXXXX0000X1ZX',
  established: 2010,
  yearsExperience: 14,
  projectsCompleted: 5000,
  citiesServed: 50,
  happyClients: 8000,
  socialLinks: {
    facebook: 'https://www.facebook.com/ameyasalescorporation',
    instagram: 'https://www.instagram.com/ameyasalescorporation',
    youtube: 'https://www.youtube.com/@ameyasalescorporation',
    linkedin: 'https://www.linkedin.com/company/ameyasalescorporation',
    twitter: 'https://twitter.com/ameyasales',
    googleMaps: 'https://maps.google.com/?q=Ameya+Sales+Corporation+Pune',
  },
  businessHours: {
    weekdays: '9:00 AM – 7:00 PM',
    saturday: '9:00 AM – 5:00 PM',
    sunday: 'Closed',
  },
  keywords: [
    'invisible grill',
    'invisible grill pune',
    'UPVC windows',
    'aluminium windows',
    'glass railing',
    'SS railing',
    'safety net',
    'bird net',
    'mosquito mesh',
    'ACP cladding',
    'pergola',
    'glass partition',
    'shower partition',
    'balcony safety',
    'window grills',
    'architectural safety solutions',
  ],
}

export const TRACKING = {
  ga4: 'G-XXXXXXXXXX',
  gtm: 'GTM-XXXXXXX',
  metaPixel: '000000000000000',
  googleAdsId: 'AW-XXXXXXXXX',
}

export const SCHEMA_DEFAULTS = {
  '@context': 'https://schema.org',
  '@type': 'LocalBusiness',
  name: 'Ameya Sales Corporation',
  url: 'https://www.ameyasalescorporation.com',
  telephone: '+91-98765-43210',
  email: 'info@ameyasalescorporation.com',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Shop No. 5, Shivaji Nagar',
    addressLocality: 'Pune',
    addressRegion: 'Maharashtra',
    postalCode: '411005',
    addressCountry: 'IN',
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: 18.5204,
    longitude: 73.8567,
  },
  openingHoursSpecification: [
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '19:00',
    },
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: 'Saturday',
      opens: '09:00',
      closes: '17:00',
    },
  ],
  priceRange: '₹₹',
  currenciesAccepted: 'INR',
  paymentAccepted: 'Cash, UPI, NEFT, RTGS, Cheque',
  areaServed: 'Maharashtra, India',
}
